import { Product } from "../types/product";


// Reusable image objects
const productImages = [
  { url: "/1.jpg", altText: "Product image 1", isPrimary: true, order: 1 },
  { url: "/2.jpg", altText: "Product image 2", isPrimary: false, order: 2 },
  { url: "/1.jpg", altText: "Product image 3", isPrimary: false, order: 3 },
];

export const MockProducts: Product[] = [
  {
    _id: "1",
    name: "Youthful Body Splash",
    brand: "Chanel",
    sellingPrice: 450.0,
    originalPrice: 520.0,
    images: productImages,
    description:
      "A timeless masculine fragrance that embodies elegance and strength with woody aromatic notes.",
    category: "luxury",
    purchasePrice: 300,
    inventory: { quantity: 10, trackInventory: true },
  },
  {
    _id: "2",
    name: "Miss Dior Blooming Bouquet",
    brand: "Dior",
    sellingPrice: 380.0,
    originalPrice: 420.0,
    images: productImages,
    description:
      "A delicate and romantic fragrance with notes of peony and rose, perfect for daytime wear.",
    category: "luxury",
    purchasePrice: 250,
    inventory: { quantity: 15, trackInventory: true },
  },
  {
    _id: "3",
    name: "Sauvage Eau de Toilette",
    brand: "Dior",
    sellingPrice: 420.0,
    originalPrice: 480.0,
    images: productImages,
    description: "A fresh, spicy fragrance with bold character and magnetic appeal.",
    category: "men",
    purchasePrice: 270,
    inventory: { quantity: 8, trackInventory: true },
  },
  {
    _id: "4",
    name: "Black Opium Eau de Parfum",
    brand: "YSL",
    sellingPrice: 390.0,
    originalPrice: 450.0,
    images: productImages,
    description: "An addictive gourmand fragrance with coffee and vanilla accents.",
    category: "luxury",
    purchasePrice: 240,
    inventory: { quantity: 12, trackInventory: true },
  },
  {
    _id: "5",
    name: "Acqua di Gio Pour Homme",
    brand: "Giorgio Armani",
    sellingPrice: 350.0,
    originalPrice: 400.0,
    images: productImages,
    description:
      "A fresh aquatic fragrance inspired by the sea and sun of Pantelleria.",
    category: "men",
    purchasePrice: 220,
    inventory: { quantity: 20, trackInventory: true },
  },
  {
    _id: "6",
    name: "Light Blue Eau Intense",
    brand: "Dolce & Gabbana",
    sellingPrice: 320.0,
    originalPrice: 370.0,
    images: productImages,
    description:
      "A vibrant Mediterranean fragrance with citrus and floral notes.",
    category: "unisex",
    purchasePrice: 200,
    inventory: { quantity: 18, trackInventory: true },
  },
  {
    _id: "7",
    name: "Good Girl Eau de Parfum",
    brand: "Carolina Herrera",
    sellingPrice: 410.0,
    originalPrice: 470.0,
    images: productImages,
    description:
      "A sensual, provocative fragrance with contrasting notes of coffee and flowers.",
    category: "luxury",
    purchasePrice: 260,
    inventory: { quantity: 6, trackInventory: true },
  },
  {
    _id: "8",
    name: "One Million Eau de Toilette",
    brand: "Paco Rabanne",
    sellingPrice: 290.0,
    originalPrice: 340.0,
    images: productImages,
    description:
      "A bold, spicy fragrance with leather and amber notes for confident men.",
    category: "men",
    purchasePrice: 180,
    inventory: { quantity: 22, trackInventory: true },
  },
  {
    _id: "9",
    name: "La Vie Est Belle Eau",
    brand: "Lancôme",
    sellingPrice: 430.0,
    originalPrice: 490.0,
    images: productImages,
    description:
      "A joyful fragrance celebrating happiness with gourmand iris notes.",
    category: "luxury",
    purchasePrice: 280,
    inventory: { quantity: 10, trackInventory: true },
  },
  {
    _id: "10",
    name: "Boss Bottled Eau de",
    brand: "Hugo Boss",
    sellingPrice: 280.0,
    originalPrice: 330.0,
    images: productImages,
    description:
      "A classic masculine fragrance with apple and cinnamon notes.",
    category: "men",
    purchasePrice: 160,
    inventory: { quantity: 14, trackInventory: true },
  },
  {
    _id: "11",
    name: "Chance Eau Tendre",
    brand: "Chanel",
    sellingPrice: 470.0,
    originalPrice: 530.0,
    images: productImages,
    description:
      "A soft, floral fragrance capturing the unexpectedness of chance.",
    category: "luxury",
    purchasePrice: 310,
    inventory: { quantity: 7, trackInventory: true },
  },
  {
    _id: "12",
    name: "Invictus Eau de Toilette",
    brand: "Paco Rabanne",
    sellingPrice: 310.0,
    originalPrice: 360.0,
    images: productImages,
    description:
      "A victorious fragrance with marine and woody notes for champions.",
    category: "men",
    purchasePrice: 190,
    inventory: { quantity: 16, trackInventory: true },
  },
  {
    _id: "13",
    name: "J'adore Eau de Parfum",
    brand: "Dior",
    sellingPrice: 440.0,
    originalPrice: 500.0,
    images: productImages,
    description:
      "A golden floral bouquet celebrating the beauty of women.",
    category: "luxury",
    purchasePrice: 290,
    inventory: { quantity: 11, trackInventory: true },
  },
  {
    _id: "14",
    name: "Body Spray Fresh",
    brand: "Nivea",
    sellingPrice: 45.0,
    originalPrice: 60.0,
    images: productImages,
    description:
      "Refreshing body spray for daily use with long-lasting freshness.",
    category: "body-sprays",
    purchasePrice: 20,
    inventory: { quantity: 30, trackInventory: false },
  },
  {
    _id: "15",
    name: "Luxury Gift Set",
    brand: "Chanel",
    sellingPrice: 680.0,
    originalPrice: 800.0,
    images: productImages,
    description:
      "Premium gift set including perfume, body lotion, and travel spray.",
    category: "gift-sets",
    purchasePrice: 400,
    inventory: { quantity: 4, trackInventory: true },
  },
  {
    _id: "16",
    name: "Sport Deodorant Spray",
    brand: "Adidas",
    sellingPrice: 35.0,
    originalPrice: 45.0,
    images: productImages,
    description:
      "High-performance deodorant for active lifestyles with 48h protection.",
    category: "body-sprays",
    purchasePrice: 15,
    inventory: { quantity: 50, trackInventory: false },
  },
];

// Auto-calc category counts
export const categories = [
  { id: "men", name: "Men's Perfumes", count: MockProducts.filter(p => p.category === "men").length },
  { id: "women", name: "Women's Perfumes", count: MockProducts.filter(p => p.category === "women").length },
  { id: "unisex", name: "Unisex", count: MockProducts.filter(p => p.category === "unisex").length },
  { id: "luxury", name: "Luxury Collection", count: MockProducts.filter(p => p.category === "luxury").length },
  { id: "body-sprays", name: "Body Sprays", count: MockProducts.filter(p => p.category === "body-sprays").length },
  { id: "gift-sets", name: "Gift Sets", count: MockProducts.filter(p => p.category === "gift-sets").length },
];
